name: Pact Provider Verify

on:
  workflow_dispatch:
    inputs:
      name:
        description: Random Name
        required: true
      home:
        description: Random Home
        required: true


jobs:
  verify-contract-requiring-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: echo ${{ github.event.inputs.name }} && echo ${{ github.event.inputs.home }}