name: Pact Provider Verify

on:
  workflow_dispatch:
    inputs:
      pactURL:
        description: URL Of The Pact.
        required: true
      consumerVersion:
        description: Version of the consumer
        required: true
      consumerName:
        description: Name of the consumer
        required: true
      consumerTags:
        description: Tags of the consumer
        required: true
      providerVersion:
        description: Version of the provider
        required: true
      message:
        description: Message to print to the console.
        required: true

env:
    GH_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
    PROVIDER_VERSION: ${{ github.sha }}
    BROKER_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
    BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
jobs:
  verify-contract-requiring-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get branch name and save to env
        run: echo "BRANCH_NAME="${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Print branch name
        run: echo ${{ env.BRANCH_NAME }}

      - name: Verify Pact
        env:
            PACT_URL: ${{ github.event.inputs.pactURL }}
            CONSUMER_VERSION: ${{ github.event.inputs.consumerVersion }}
            CONSUMER_NAME: ${{ github.event.inputs.consumerName }}
            CONSUMER_TAGS: ${{ github.event.inputs.consumerTags }}
            PROVIDER_BRANCH: ${{ env.BRANCH_NAME }}
            PACT_BROKER_BASE_URL: $BROKER_URL
            PACT_BROKER_TOKEN: $BROKER_TOKEN
            PROVIDER_VERSION: ${{ github.event.inputs.providerVersion }}
        run: echo ${{ github.event.inputs.message }} && go clean -testcache && go test -tags=provider ./app/... -v
